### ISSUE TITLE
[Bug]: A test bug report

### ISSUE THREAD

**Issue by botgina** [mkeithX/mkeithx.github.io#173]
### Basic troubleshooting.

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### What happened?

A bug happened when filling out this test issue

### Steps to reproduce

Test item 1 2 3 and 5

### What browsers are you seeing the problem on?

Brave

### Device type.

Desktop

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### Self-service

- [X] I'd be willing to address this documentation request myself.

**Comment by mkeithX** [comment]
Thanks @botgina
