### ISSUE TITLE
[Docs]: Code of Conduct checkbox

### ISSUE THREAD

**Issue by botgina** [mkeithX/mkeithx.github.io#174]
### Issue category

Formatting or readability improvement

### Description

See screenshot:

![image](https://github.com/user-attachments/assets/a3ac2fc5-4655-4f51-8f2f-f5ffac807d75)

### Have you read the Contributing Guidelines on [reporting issues](https://mkeithx.pages.dev/community/report-an-issue)?

- [X] I have read the [Code of Conduct](https://github.com/mkeithX/mkeithx.github.io/blob/main/CONTRIBUTING.md).

### Self-service

- [X] I'd be willing to address this documentation request myself.

**Comment by mkeithX** [comment]
Awesome. Thank you for reporting this @botgina
