### ISSUE TITLE
[Bug]: Testing Bug Report Template Functionality

### ISSUE THREAD

**Issue by botgina** [mkeithX/mkeithx.github.io#186]
### Prerequisites

- [X] I have read the Guidelines in [reporting bugs](https://mkeithx.pages.dev/community/issue/report).
- [X] I have performed [basic troubleshooting](https://mkeithx.pages.dev/community/issue/style-guide/troubleshoot) (if applicable).
- [X] I'd be willing to address this issue myself.

### What happened?

As requested, this report is the test the "Bug Report" template to ensure everything is working as intended. See attached screenshot - describing the footer of this website:

![image](https://github.com/user-attachments/assets/a333e67b-ec45-459a-9ba7-ed4b7f5db7ef)

### Steps to reproduce

1. Open the website in Chrome.
2. Scroll to the footer section of the homepage.
3. Observe the content and layout of the footer.

### What browsers are you seeing the problem on?

Chrome

### Device type.

Desktop

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by mkeithX** [comment]
Nicely done @botgina . Thank you!

**Comment by mkeithX** [comment]
Closing this on the next PR @botgina
