### ISSUE TITLE
[Docs]: Docs Report Template Functionality - Test

### ISSUE THREAD

**Issue by botgina** [mkeithX/mkeithx.github.io#187]
### What's this about?

Outdated or incorrect information

### Description

This report is intended to test the functionality of the Documentation Report Template to ensure all elements are working as expected. -As requested

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### Self-service

- [X] I'd be willing to address this documentation request myself.

**Comment by mkeithX** [comment]
Awesome @botgina. Thank you!

**Comment by mkeithX** [comment]
Closing this on the next PR @botgina
